register javascript update 1
shu1513/tangobookings pull request #3
Opened 2024-04-21 19:37 UTC by shu1513

trying to use pull request. 

Instead of using oninput and onsubmit with html, I used addEventListener and "DOMContentLoaded" in the javascript

2024-04-21 19:40 UTC, nathanieltsmith requested changes
You probably want to add the binary files to .gitignore file and remove them from the PR. so they aren't kept in version control

2024-04-22 05:08 UTC, shu1513 reviewed
I changed a lot of things including hid 2 directories of binary files into .gitignore

2024-04-22 05:08 UTC, shu1513 commented on static/register_script.js
deleted unused codes.

2024-04-22 05:08 UTC, shu1513 commented on templates/register.html
get rid of javascript from the html page.

2024-04-23 05:59 UTC, merged